version: 2

sources:
  - name: snowflake_sample
    database: dbt_train_db
    schema: dbt_train_jaffle_shop

    tables:
      - name: raw_orders 
      - name: raw_payments
      - name: raw_customers